#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Wed Aug 12 09:40:03 GMT 2026
org.gradle.caching=true
android.uniquePackageNames=false
android.nonTransitiveRClass=true
android.dependency.useConstraints=true
android.builtInKotlin=false
org.gradle.daemon.idletimeout=10800000
org.gradle.parallel=true
android.useAndroidX=true
ksp.useKSP2=false
android.r8.optimizedResourceShrinking=false
android.defaults.buildfeatures.resvalues=true
android.r8.strictFullModeForKeepRules=false
android.newDsl=false
systemProp.file.encoding=UTF-8
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
systemProp.user.language=en
systemProp.user.country=US
org.gradle.tooling.parallel=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -Dsun.zip.disableMemoryMapping\=true -Djdk.nio.zipfs.disableMemoryMapping\=true
org.gradle.vfs.watch=false
kotlin.code.style=official
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
systemProp.sun.jnu.encoding=UTF-8
