package com.playfieldportal.feature.settings.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.IntentType
import com.playfieldportal.feature.launcher.EmulatorProfileRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.UUID
import javax.inject.Inject

data class ProfileListItem(
    val id: String,
    val name: String,
    val packageName: String,
    val intentType: String,
    val isCustom: Boolean,
    val isAutoGenerated: Boolean = false,
    val isAvailable: Boolean = true,
    val userModified: Boolean = false,
    val autoSource: String? = null,
)

data class ProfileEditorState(
    val isNew: Boolean,
    val originalId: String?,
    val isAutoGenerated: Boolean = false,
    val name: String = "",
    val packageName: String = "",
    val activityClass: String = "",
    val intentType: IntentType = IntentType.ACTION_VIEW,
    val supportedPlatformIds: String = "",  // comma-separated
    val mimeType: String = "",
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String = "",
    val notes: String = "",
    val isSaving: Boolean = false,
    val errorMessage: String? = null,
)

const val ADD_CUSTOM_EMULATOR_FOCUS_KEY = "add_custom_emulator"

data class EmulatorsSettingsUiState(
    val installedProfiles: List<ProfileListItem> = emptyList(),
    val availableProfiles: List<ProfileListItem> = emptyList(),
    val customProfiles: List<ProfileListItem> = emptyList(),
    val editorState: ProfileEditorState? = null,
    val returnFocusKey: String? = null,
    val showResetConfirm: Boolean = false,
    val isResetting: Boolean = false,
)

@HiltViewModel
class EmulatorsSettingsViewModel @Inject constructor(
    private val profileRepository: EmulatorProfileRepository,
) : ViewModel() {

    private val _uiState = MutableStateFlow(EmulatorsSettingsUiState())
    val uiState: StateFlow<EmulatorsSettingsUiState> = _uiState.asStateFlow()

    private var allProfiles: List<EmulatorProfile> = emptyList()

    init {
        observeProfiles()
    }

    private fun observeProfiles() {
        viewModelScope.launch {
            profileRepository.profiles.collect { all ->
                allProfiles = all
                val installed = profileRepository.getInstalledProfiles()
                val custom    = all.filter { it.isCustom && !it.isAutoGenerated }
                val available = all.filter { p ->
                    !p.isCustom && !p.isAutoGenerated &&
                    installed.none { it.packageName == p.packageName }
                }
                _uiState.update {
                    it.copy(
                        installedProfiles = installed.map { p -> p.toListItem() },
                        availableProfiles = available.map { p -> p.toListItem() },
                        customProfiles    = custom.map { p -> p.toListItem() },
                    )
                }
            }
        }
    }

    fun openEditor(profileId: String?) {
        val profile = profileId?.let { id -> allProfiles.firstOrNull { it.id == id } }
        _uiState.update {
            it.copy(
                returnFocusKey = profileId ?: ADD_CUSTOM_EMULATOR_FOCUS_KEY,
                editorState    = if (profile != null) {
                    ProfileEditorState(
                        isNew                = false,
                        originalId           = profile.id,
                        isAutoGenerated      = profile.isAutoGenerated,
                        name                 = profile.name,
                        packageName          = profile.packageName,
                        activityClass        = profile.activityClass ?: "",
                        intentType           = profile.intentType,
                        supportedPlatformIds = profile.supportedPlatformIds.joinToString(","),
                        mimeType             = profile.mimeType ?: "",
                        useFileUri           = profile.useFileUri,
                        useSafUri            = profile.useSafUri,
                        customCommand        = profile.customCommand ?: "",
                        notes                = profile.notes ?: "",
                    )
                } else {
                    ProfileEditorState(isNew = true, originalId = null)
                },
            )
        }
    }

    fun closeEditor() {
        _uiState.update { it.copy(editorState = null) }
    }

    fun updateEditorName(value: String)           = updateEditor { copy(name = value, errorMessage = null) }
    fun updateEditorPackageName(value: String)    = updateEditor { copy(packageName = value, errorMessage = null) }
    fun updateEditorActivityClass(value: String)  = updateEditor { copy(activityClass = value) }
    fun updateEditorIntentType(value: IntentType) = updateEditor { copy(intentType = value) }
    fun updateEditorPlatformIds(value: String)    = updateEditor { copy(supportedPlatformIds = value) }
    fun updateEditorMimeType(value: String)       = updateEditor { copy(mimeType = value) }
    fun updateEditorUseFileUri(value: Boolean)    = updateEditor { copy(useFileUri = value) }
    fun updateEditorUseSafUri(value: Boolean)     = updateEditor { copy(useSafUri = value) }
    fun updateEditorCustomCommand(value: String)  = updateEditor { copy(customCommand = value) }
    fun updateEditorNotes(value: String)          = updateEditor { copy(notes = value) }

    private fun updateEditor(block: ProfileEditorState.() -> ProfileEditorState) {
        _uiState.update { state -> state.copy(editorState = state.editorState?.block()) }
    }

    fun saveEditorProfile() {
        val editor = _uiState.value.editorState ?: return
        if (editor.name.isBlank()) {
            updateEditor { copy(errorMessage = "Name is required") }
            return
        }
        if (editor.packageName.isBlank() && editor.intentType != IntentType.CUSTOM_COMMAND) {
            updateEditor { copy(errorMessage = "Package name is required") }
            return
        }
        updateEditor { copy(isSaving = true, errorMessage = null) }
        viewModelScope.launch {
            val existing = editor.originalId?.let { id -> allProfiles.firstOrNull { it.id == id } }
            val profile = EmulatorProfile(
                id                   = editor.originalId ?: UUID.randomUUID().toString(),
                name                 = editor.name.trim(),
                packageName          = editor.packageName.trim(),
                activityClass        = editor.activityClass.trimToNull(),
                intentType           = editor.intentType,
                supportedPlatformIds = editor.supportedPlatformIds
                    .split(",").map { it.trim() }.filter { it.isNotEmpty() },
                mimeType             = editor.mimeType.trimToNull(),
                useFileUri           = editor.useFileUri,
                useSafUri            = editor.useSafUri,
                customCommand        = editor.customCommand.trimToNull(),
                notes                = editor.notes.trimToNull(),
                isCustom             = true,
                // Preserve auto-gen metadata; mark as user-modified so auto-config skips it
                isAutoGenerated      = existing?.isAutoGenerated ?: false,
                autoSource           = existing?.autoSource,
                lastDetectedAt       = existing?.lastDetectedAt,
                userModified         = true,
                isAvailable          = existing?.isAvailable ?: true,
            )
            profileRepository.savePersistedProfile(profile)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun deleteProfile(id: String) {
        viewModelScope.launch {
            profileRepository.deleteCustomProfile(id)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun requestResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = true) }
    }

    fun cancelResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false) }
    }

    fun confirmResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false, isResetting = true) }
        viewModelScope.launch {
            profileRepository.resetPersistedProfiles()
            _uiState.update { it.copy(isResetting = false) }
        }
    }

    private fun EmulatorProfile.toListItem() = ProfileListItem(
        id             = id,
        name           = name,
        packageName    = packageName,
        intentType     = intentType.name,
        isCustom       = isCustom,
        isAutoGenerated = isAutoGenerated,
        isAvailable    = isAvailable,
        userModified   = userModified,
        autoSource     = autoSource,
    )

    private fun String.trimToNull() = trim().ifEmpty { null }
}
