package com.playfieldportal.feature.settings.viewmodel

import android.content.Context
import android.content.Intent
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.Game
import com.playfieldportal.core.domain.model.IntentType
import com.playfieldportal.core.domain.repository.GameRepository
import kotlinx.coroutines.flow.first
import com.playfieldportal.feature.launcher.AppLaunchInspector
import com.playfieldportal.feature.launcher.DetectableApp
import com.playfieldportal.feature.launcher.EmulatorIntentResolver
import com.playfieldportal.feature.launcher.EmulatorProfileRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.UUID
import javax.inject.Inject

data class ProfileListItem(
    val id: String,
    val name: String,
    val packageName: String,
    val intentType: String,
    val isCustom: Boolean,
    val isAutoGenerated: Boolean = false,
    val isAvailable: Boolean = true,
    val userModified: Boolean = false,
    val autoSource: String? = null,
)

data class ProfileEditorState(
    val isNew: Boolean,
    val originalId: String?,
    val isAutoGenerated: Boolean = false,
    val name: String = "",
    val packageName: String = "",
    val activityClass: String = "",
    val intentType: IntentType = IntentType.ACTION_VIEW,
    val supportedPlatformIds: String = "",  // comma-separated
    val mimeType: String = "",
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String = "",
    val notes: String = "",
    val isSaving: Boolean = false,
    val errorMessage: String? = null,
    // Wizard banner explaining detection confidence (null = plain edit).
    val detectionNote: String? = null,
    // Advanced launch fields carried opaquely so wizard prefills / auto-gen profiles are not lost
    // on save. The form doesn't edit these yet, but a read-only summary is shown when present.
    val intentExtras: Map<String, String> = emptyMap(),
    val intentBoolExtras: Map<String, Boolean> = emptyMap(),
    val intentAction: String? = null,
    val intentFlags: List<String> = emptyList(),
    val intentCategory: String? = null,
    val coreMap: Map<String, String> = emptyMap(),
)

const val ADD_CUSTOM_EMULATOR_FOCUS_KEY = "add_custom_emulator"

// ── Test launch (wizard step) ──────────────────────────────────────────────────

data class TestRom(
    val gameId: Long,
    val title: String,
    val platformId: String,
)

// Safe, user-readable summary of the intent the draft profile would fire.
data class IntentPreview(
    val packageName: String,
    val activity: String?,
    val action: String,
    val mimeType: String?,
    val uriMode: String,
    val romRef: String,
    val extras: List<String>,
    val flags: List<String>,
)

data class TestLaunchState(
    val roms: List<TestRom> = emptyList(),
    val selectedRom: TestRom? = null,
    val preview: IntentPreview? = null,
    val resultMessage: String? = null,
    val isError: Boolean = false,
    val canLaunch: Boolean = false,
)

data class EmulatorsSettingsUiState(
    val installedProfiles: List<ProfileListItem> = emptyList(),
    val availableProfiles: List<ProfileListItem> = emptyList(),
    val customProfiles: List<ProfileListItem> = emptyList(),
    val editorState: ProfileEditorState? = null,
    // Non-null while the "Add Custom Emulator" wizard is on its Pick-App step.
    val wizardApps: List<DetectableApp>? = null,
    val isInspecting: Boolean = false,
    // Non-null while testing a draft profile against a ROM.
    val testLaunch: TestLaunchState? = null,
    val returnFocusKey: String? = null,
    val showResetConfirm: Boolean = false,
    val isResetting: Boolean = false,
)

@HiltViewModel
class EmulatorsSettingsViewModel @Inject constructor(
    private val profileRepository: EmulatorProfileRepository,
    private val appLaunchInspector: AppLaunchInspector,
    private val gameRepository: GameRepository,
    private val intentResolver: EmulatorIntentResolver,
    @ApplicationContext private val appContext: Context,
) : ViewModel() {

    private val _uiState = MutableStateFlow(EmulatorsSettingsUiState())
    val uiState: StateFlow<EmulatorsSettingsUiState> = _uiState.asStateFlow()

    private var allProfiles: List<EmulatorProfile> = emptyList()
    // Holds the built, launchable test intent (kept out of UI state — Intents aren't UI data).
    private var testIntent: Intent? = null

    init {
        observeProfiles()
    }

    private fun observeProfiles() {
        viewModelScope.launch {
            profileRepository.profiles.collect { all ->
                allProfiles = all
                val installed = profileRepository.getInstalledProfiles()
                val custom    = all.filter { it.isCustom && !it.isAutoGenerated }
                val available = all.filter { p ->
                    !p.isCustom && !p.isAutoGenerated &&
                    installed.none { it.packageName == p.packageName }
                }
                _uiState.update {
                    it.copy(
                        installedProfiles = installed.map { p -> p.toListItem() },
                        availableProfiles = available.map { p -> p.toListItem() },
                        customProfiles    = custom.map { p -> p.toListItem() },
                    )
                }
            }
        }
    }

    fun openEditor(profileId: String?) {
        val profile = profileId?.let { id -> allProfiles.firstOrNull { it.id == id } }
        _uiState.update {
            it.copy(
                returnFocusKey = profileId ?: ADD_CUSTOM_EMULATOR_FOCUS_KEY,
                editorState    = if (profile != null) editorStateFor(profile, isNew = false, detectionNote = null)
                                 else ProfileEditorState(isNew = true, originalId = null),
            )
        }
    }

    // ── Add Custom Emulator wizard ─────────────────────────────────────────────

    /** Step 1: present the controller-navigable list of installed apps to pick from. */
    fun startAddEmulatorWizard() {
        _uiState.update { it.copy(returnFocusKey = ADD_CUSTOM_EMULATOR_FOCUS_KEY, isInspecting = true) }
        viewModelScope.launch {
            val apps = withContext(Dispatchers.IO) { appLaunchInspector.listLaunchableApps() }
            _uiState.update { it.copy(wizardApps = apps, isInspecting = false) }
        }
    }

    /** Step 2: inspect the chosen app and open the editor pre-filled with the best-guess draft. */
    fun selectWizardApp(packageName: String) {
        _uiState.update { it.copy(isInspecting = true) }
        viewModelScope.launch {
            val suggestion = withContext(Dispatchers.IO) { appLaunchInspector.suggestForPackage(packageName) }
            _uiState.update {
                it.copy(
                    wizardApps = null,
                    isInspecting = false,
                    editorState = editorStateFor(suggestion.profile, isNew = true, detectionNote = suggestion.note),
                )
            }
        }
    }

    fun cancelWizard() {
        _uiState.update { it.copy(wizardApps = null, isInspecting = false) }
    }

    private fun editorStateFor(profile: EmulatorProfile, isNew: Boolean, detectionNote: String?) =
        ProfileEditorState(
            isNew                = isNew,
            originalId           = if (isNew) null else profile.id,
            isAutoGenerated      = profile.isAutoGenerated,
            name                 = profile.name,
            packageName          = profile.packageName,
            activityClass        = profile.activityClass ?: "",
            intentType           = profile.intentType,
            supportedPlatformIds = profile.supportedPlatformIds.joinToString(","),
            mimeType             = profile.mimeType ?: "",
            useFileUri           = profile.useFileUri,
            useSafUri            = profile.useSafUri,
            customCommand        = profile.customCommand ?: "",
            notes                = profile.notes ?: "",
            detectionNote        = detectionNote,
            intentExtras         = profile.intentExtras,
            intentBoolExtras     = profile.intentBoolExtras,
            intentAction         = profile.intentAction,
            intentFlags          = profile.intentFlags,
            intentCategory       = profile.intentCategory,
            coreMap              = profile.coreMap,
        )

    // ── Test launch ────────────────────────────────────────────────────────────

    /** Loads the user's scanned ROMs to pick a test target (controller-navigable list). */
    fun startTestLaunch() {
        if (_uiState.value.editorState == null) return
        viewModelScope.launch {
            val roms = withContext(Dispatchers.IO) {
                gameRepository.observeGamesOnly().first()
                    .filter { !it.romPath.isNullOrBlank() }
                    .map { TestRom(it.id, it.displayTitle, it.platformId) }
                    .sortedBy { it.title.lowercase() }
            }
            _uiState.update { it.copy(testLaunch = TestLaunchState(roms = roms)) }
        }
    }

    /** Builds the intent from the current draft + chosen ROM, shows a preview, and reports whether
     *  it resolves. Does NOT launch yet — the user confirms with [launchTest]. */
    fun selectTestRom(gameId: Long) {
        val editor = _uiState.value.editorState ?: return
        val test = _uiState.value.testLaunch ?: return
        val rom = test.roms.firstOrNull { it.gameId == gameId } ?: return
        viewModelScope.launch {
            val game = withContext(Dispatchers.IO) { gameRepository.getById(gameId) }
            if (game == null) {
                _uiState.update { it.copy(testLaunch = test.copy(selectedRom = rom, resultMessage = "Could not load that ROM.", isError = true)) }
                return@launch
            }
            val profile = editor.draftProfile()
            val preview = buildPreview(profile, game)
            val result = withContext(Dispatchers.IO) { intentResolver.resolve(game, profile) }
            result.fold(
                onSuccess = { intent ->
                    testIntent = intent
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = "Resolves OK — press Launch Now to try it.",
                        isError = false, canLaunch = true,
                    )) }
                },
                onFailure = { e ->
                    testIntent = null
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = mapLaunchError(e), isError = true, canLaunch = false,
                    )) }
                },
            )
        }
    }

    fun launchTest() {
        val intent = testIntent ?: return
        val test = _uiState.value.testLaunch ?: return
        runCatching {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            appContext.startActivity(intent)
        }.onSuccess {
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = "Launched — check the emulator.", isError = false)) }
        }.onFailure { e ->
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = mapLaunchError(e), isError = true, canLaunch = false)) }
        }
    }

    fun pickDifferentTestRom() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = it.testLaunch?.copy(
            selectedRom = null, preview = null, resultMessage = null, isError = false, canLaunch = false,
        )) }
    }

    fun closeTestLaunch() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = null) }
    }

    private fun ProfileEditorState.draftProfile() = EmulatorProfile(
        id                   = originalId ?: "draft_test",
        name                 = name.trim().ifEmpty { packageName },
        packageName          = packageName.trim(),
        activityClass        = activityClass.trimToNull(),
        intentType           = intentType,
        supportedPlatformIds = supportedPlatformIds.split(",").map { it.trim() }.filter { it.isNotEmpty() },
        mimeType             = mimeType.trimToNull(),
        useFileUri           = useFileUri,
        useSafUri            = useSafUri,
        customCommand        = customCommand.trimToNull(),
        intentExtras         = intentExtras,
        intentBoolExtras     = intentBoolExtras,
        intentAction         = intentAction,
        intentFlags          = intentFlags,
        intentCategory       = intentCategory,
        coreMap              = coreMap,
        isCustom             = true,
    )

    private fun buildPreview(profile: EmulatorProfile, game: Game): IntentPreview {
        val uriMode = when {
            profile.intentType == IntentType.CUSTOM_COMMAND -> "custom command"
            profile.useSafUri  -> "content:// (FileProvider, read granted)"
            profile.useFileUri -> "file:// (content:// on API 24+)"
            else               -> "content://"
        }
        val action = when (profile.intentType) {
            IntentType.ACTION_VIEW    -> "android.intent.action.VIEW"
            IntentType.COMPONENT      -> profile.intentAction ?: "android.intent.action.MAIN"
            IntentType.CUSTOM_COMMAND -> "(custom command)"
            IntentType.SHORTCUT       -> "(shortcut)"
        }
        val extras = buildList {
            profile.intentExtras.forEach { (k, v) -> add("$k = $v") }
            profile.intentBoolExtras.forEach { (k, v) -> add("$k = $v") }
        }
        return IntentPreview(
            packageName = profile.packageName,
            activity    = profile.activityClass,
            action      = action,
            mimeType    = profile.mimeType,
            uriMode     = uriMode,
            romRef      = game.romPath ?: game.packageName ?: "(none)",
            extras      = extras,
            flags       = profile.intentFlags,
        )
    }

    // Maps resolver failures and startActivity exceptions to the spec's actionable error cases.
    private fun mapLaunchError(e: Throwable): String {
        val msg = e.message.orEmpty()
        return when {
            e is android.content.ActivityNotFoundException ->
                "Activity not found or not exported. Check the activity name, or try ACTION_VIEW instead."
            e is SecurityException ->
                "Permission denied — the app rejected the ROM URI. Try toggling SAF (content://) vs file URI."
            msg.contains("not installed", ignoreCase = true)      -> msg
            msg.contains("ROM file not found", ignoreCase = true)  -> msg
            msg.contains("ROM path is required", ignoreCase = true) -> msg
            msg.contains("core", ignoreCase = true)                -> msg   // missing RetroArch core
            msg.contains("cannot open this ROM", ignoreCase = true) ->
                "$msg The app didn't accept this MIME type / URI mode — try the other URI mode."
            msg.isNotBlank()                                       -> msg
            else                                                  -> "Launch failed for an unknown reason."
        }
    }

    fun closeEditor() {
        _uiState.update { it.copy(editorState = null) }
    }

    fun updateEditorName(value: String)           = updateEditor { copy(name = value, errorMessage = null) }
    fun updateEditorPackageName(value: String)    = updateEditor { copy(packageName = value, errorMessage = null) }
    fun updateEditorActivityClass(value: String)  = updateEditor { copy(activityClass = value) }
    fun updateEditorIntentType(value: IntentType) = updateEditor { copy(intentType = value) }
    fun updateEditorPlatformIds(value: String)    = updateEditor { copy(supportedPlatformIds = value) }
    fun updateEditorMimeType(value: String)       = updateEditor { copy(mimeType = value) }
    fun updateEditorUseFileUri(value: Boolean)    = updateEditor { copy(useFileUri = value) }
    fun updateEditorUseSafUri(value: Boolean)     = updateEditor { copy(useSafUri = value) }
    fun updateEditorCustomCommand(value: String)  = updateEditor { copy(customCommand = value) }
    fun updateEditorNotes(value: String)          = updateEditor { copy(notes = value) }

    private fun updateEditor(block: ProfileEditorState.() -> ProfileEditorState) {
        _uiState.update { state -> state.copy(editorState = state.editorState?.block()) }
    }

    fun saveEditorProfile() {
        val editor = _uiState.value.editorState ?: return
        if (editor.name.isBlank()) {
            updateEditor { copy(errorMessage = "Name is required") }
            return
        }
        if (editor.packageName.isBlank() && editor.intentType != IntentType.CUSTOM_COMMAND) {
            updateEditor { copy(errorMessage = "Package name is required") }
            return
        }
        updateEditor { copy(isSaving = true, errorMessage = null) }
        viewModelScope.launch {
            val existing = editor.originalId?.let { id -> allProfiles.firstOrNull { it.id == id } }
            val profile = EmulatorProfile(
                id                   = editor.originalId ?: UUID.randomUUID().toString(),
                name                 = editor.name.trim(),
                packageName          = editor.packageName.trim(),
                activityClass        = editor.activityClass.trimToNull(),
                intentType           = editor.intentType,
                supportedPlatformIds = editor.supportedPlatformIds
                    .split(",").map { it.trim() }.filter { it.isNotEmpty() },
                mimeType             = editor.mimeType.trimToNull(),
                useFileUri           = editor.useFileUri,
                useSafUri            = editor.useSafUri,
                customCommand        = editor.customCommand.trimToNull(),
                notes                = editor.notes.trimToNull(),
                // Carried opaquely from the wizard/auto-gen source so prefilled launch details
                // (extras, flags, action, category, RetroArch core map) survive the save.
                intentExtras         = editor.intentExtras,
                intentBoolExtras     = editor.intentBoolExtras,
                intentAction         = editor.intentAction,
                intentFlags          = editor.intentFlags,
                intentCategory       = editor.intentCategory,
                coreMap              = editor.coreMap,
                isCustom             = true,
                // Preserve auto-gen metadata; mark as user-modified so auto-config skips it
                isAutoGenerated      = existing?.isAutoGenerated ?: false,
                autoSource           = existing?.autoSource,
                lastDetectedAt       = existing?.lastDetectedAt,
                userModified         = true,
                isAvailable          = existing?.isAvailable ?: true,
            )
            profileRepository.savePersistedProfile(profile)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun deleteProfile(id: String) {
        viewModelScope.launch {
            profileRepository.deleteCustomProfile(id)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun requestResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = true) }
    }

    fun cancelResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false) }
    }

    fun confirmResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false, isResetting = true) }
        viewModelScope.launch {
            profileRepository.resetPersistedProfiles()
            _uiState.update { it.copy(isResetting = false) }
        }
    }

    private fun EmulatorProfile.toListItem() = ProfileListItem(
        id             = id,
        name           = name,
        packageName    = packageName,
        intentType     = intentType.name,
        isCustom       = isCustom,
        isAutoGenerated = isAutoGenerated,
        isAvailable    = isAvailable,
        userModified   = userModified,
        autoSource     = autoSource,
    )

    private fun String.trimToNull() = trim().ifEmpty { null }
}
