package com.playfieldportal.feature.launcher

import android.content.Context
import android.content.pm.PackageInfo
import androidx.test.core.app.ApplicationProvider
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.IntentType
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.Shadows.shadowOf
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Startup reconciliation between the catalog and persisted profiles. The critical behavior:
 * untouched auto-profiles must adopt corrected catalog recipes on upgrade, while anything
 * the user edited or created stays untouched.
 */
@RunWith(RobolectricTestRunner::class)
class EmulatorAutoConfigServiceTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val repository = EmulatorProfileRepository(context, Dispatchers.Unconfined)
    // Unlinked RetroArch (no stored tree) → installedCoreFiles() is null → curated cores offered.
    private val service = EmulatorAutoConfigService(
        EmulatorDetector(context),
        repository,
        com.playfieldportal.core.data.repository.RetroArchLink(context),
    )

    private fun installPackage(packageName: String) {
        shadowOf(context.packageManager)
            .installPackage(PackageInfo().apply { this.packageName = packageName })
    }

    private suspend fun persistedById(id: String): EmulatorProfile =
        repository.getAllPersistedProfiles().first { it.id == id }

    @Test
    fun `untouched auto profile adopts the corrected catalog recipe`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        val staleId = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = staleId,
                name = "DuckStation",
                packageName = "com.github.stenzek.duckstation",
                activityClass = "com.github.stenzek.duckstation.EmulationActivity",
                intentType = IntentType.COMPONENT,
                supportedPlatformIds = listOf("psx", "ps1"),
                intentExtras = mapOf("bootPath" to "{rom_path}"), // pre-fix raw-path recipe
                isAutoGenerated = true,
                createdAt = 1234L,
            )
        )

        service.runOnStartup()

        val refreshed = persistedById(staleId)
        assertEquals(
            "{rom_uri}", refreshed.intentExtras["bootPath"],
            "Stale recipe should be replaced by the current catalog recipe",
        )
        assertEquals(1234L, refreshed.createdAt, "Creation time must survive the refresh")
        assertTrue(refreshed.isAvailable)
        assertFalse(refreshed.userModified)
    }

    @Test
    fun `user modified auto profile is left untouched`() = runBlocking {
        installPackage("me.magnum.melonds")
        val id = EmulatorDetector.autoId("me.magnum.melonds")
        val edited = EmulatorProfile(
            id = id,
            name = "melonDS (my tweaks)",
            packageName = "me.magnum.melonds",
            activityClass = "me.magnum.melonds.ui.emulator.EmulatorActivity",
            intentType = IntentType.COMPONENT,
            supportedPlatformIds = listOf("nds"),
            intentExtras = mapOf("uri" to "{rom_uri}", "myCustomExtra" to "keep-me"),
            isAutoGenerated = true,
            userModified = true,
        )
        repository.savePersistedProfile(edited)

        service.runOnStartup()

        val after = persistedById(id)
        assertEquals("melonDS (my tweaks)", after.name)
        assertEquals("keep-me", after.intentExtras["myCustomExtra"])
    }

    @Test
    fun `custom profile is never reconciled against the catalog`() = runBlocking {
        val custom = EmulatorProfile(
            id = "custom_my_fork",
            name = "My Fork",
            packageName = "com.example.myfork",
            intentType = IntentType.ACTION_VIEW,
            supportedPlatformIds = listOf("psx"),
            isCustom = true,
        )
        repository.savePersistedProfile(custom)

        service.runOnStartup()

        val after = persistedById("custom_my_fork")
        assertEquals("My Fork", after.name)
        assertTrue(after.isAvailable, "Custom profiles must not be marked unavailable")
    }

    @Test
    fun `auto profile for an uninstalled emulator is marked unavailable`() = runBlocking {
        val id = EmulatorDetector.autoId("org.ppsspp.ppsspp")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = id,
                name = "PPSSPP",
                packageName = "org.ppsspp.ppsspp",
                intentType = IntentType.ACTION_VIEW,
                supportedPlatformIds = listOf("psp"),
                isAutoGenerated = true,
                isAvailable = true,
            )
        )

        service.runOnStartup()

        assertFalse(persistedById(id).isAvailable)
    }

    // Regression: the old detector scanned /storage/emulated/0/RetroArch/cores, which never exists
    // on a modern install (cores live in RetroArch's private internal dir), so it produced zero
    // profiles and every RetroArch console was unlaunchable.
    @Test
    fun `retroarch profiles are offered without a readable cores directory`() {
        installPackage("com.retroarch")

        val profiles = EmulatorDetector(context).detect()
            .filter { it.autoSource == "retroarch-core" }

        assertTrue(profiles.isNotEmpty(), "No RetroArch core profiles offered")
        val snes = profiles.firstOrNull { "snes" in it.supportedPlatformIds }
        assertTrue(snes != null, "No RetroArch profile covers SNES")
        assertEquals("com.retroarch", snes!!.packageName)
        assertEquals(IntentType.COMPONENT, snes.intentType)
        assertEquals(
            "/data/data/com.retroarch/cores/snes9x_libretro_android.so",
            snes.intentExtras["LIBRETRO"],
            "LIBRETRO must name RetroArch's internal core path",
        )
        assertEquals(snes.intentExtras["LIBRETRO"], snes.coreMap["snes"])
    }

    @Test
    fun `curated retroarch cores cover the seeded 2D platforms`() {
        installPackage("com.retroarch")
        val covered = EmulatorDetector(context).detect()
            .filter { it.autoSource == "retroarch-core" }
            .flatMap { it.supportedPlatformIds }
            .toSet()

        for (platform in listOf(
            "nes", "snes", "n64", "gb", "gbc", "gba", "megadrive", "mastersystem",
            "gamegear", "sega32x", "segacd", "saturn", "psx", "pcengine", "neogeo",
            "ngp", "wonderswan", "atari2600", "atari5200", "atari7800", "atarilynx",
            "virtualboy", "c64", "mame",
        )) {
            assertTrue(platform in covered, "No RetroArch core offered for '$platform'")
        }
    }

    @Test
    fun `detector maps attachRomData through to the profile`() {
        installPackage("dev.eden.eden_emulator")

        val eden = EmulatorDetector(context).detect()
            .first { it.packageName == "dev.eden.eden_emulator" }

        assertEquals(IntentType.COMPONENT, eden.intentType)
        assertEquals("android.nfc.action.TECH_DISCOVERED", eden.intentAction)
        assertTrue(eden.attachRomData, "attachRomData lost between catalog and profile")
        assertEquals("org.yuzu.yuzu_emu.activities.EmulationActivity", eden.activityClass)
    }
}
