package com.playfieldportal.feature.launcher

import android.content.Context
import android.content.pm.PackageInfo
import androidx.test.core.app.ApplicationProvider
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.IntentType
import kotlinx.coroutines.runBlocking
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.Shadows.shadowOf
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Startup reconciliation between the catalog and persisted profiles. The critical behavior:
 * untouched auto-profiles must adopt corrected catalog recipes on upgrade, while anything
 * the user edited or created stays untouched.
 */
@RunWith(RobolectricTestRunner::class)
class EmulatorAutoConfigServiceTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val repository = EmulatorProfileRepository(context)
    private val service = EmulatorAutoConfigService(EmulatorDetector(context), repository)

    private fun installPackage(packageName: String) {
        shadowOf(context.packageManager)
            .installPackage(PackageInfo().apply { this.packageName = packageName })
    }

    private fun persistedById(id: String): EmulatorProfile =
        repository.getAllPersistedProfiles().first { it.id == id }

    @Test
    fun `untouched auto profile adopts the corrected catalog recipe`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        val staleId = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = staleId,
                name = "DuckStation",
                packageName = "com.github.stenzek.duckstation",
                activityClass = "com.github.stenzek.duckstation.EmulationActivity",
                intentType = IntentType.COMPONENT,
                supportedPlatformIds = listOf("psx", "ps1"),
                intentExtras = mapOf("bootPath" to "{rom_path}"), // pre-fix raw-path recipe
                isAutoGenerated = true,
                createdAt = 1234L,
            )
        )

        service.runOnStartup()

        val refreshed = persistedById(staleId)
        assertEquals(
            "{rom_uri}", refreshed.intentExtras["bootPath"],
            "Stale recipe should be replaced by the current catalog recipe",
        )
        assertEquals(1234L, refreshed.createdAt, "Creation time must survive the refresh")
        assertTrue(refreshed.isAvailable)
        assertFalse(refreshed.userModified)
    }

    @Test
    fun `user modified auto profile is left untouched`() = runBlocking {
        installPackage("me.magnum.melonds")
        val id = EmulatorDetector.autoId("me.magnum.melonds")
        val edited = EmulatorProfile(
            id = id,
            name = "melonDS (my tweaks)",
            packageName = "me.magnum.melonds",
            activityClass = "me.magnum.melonds.ui.emulator.EmulatorActivity",
            intentType = IntentType.COMPONENT,
            supportedPlatformIds = listOf("nds"),
            intentExtras = mapOf("uri" to "{rom_uri}", "myCustomExtra" to "keep-me"),
            isAutoGenerated = true,
            userModified = true,
        )
        repository.savePersistedProfile(edited)

        service.runOnStartup()

        val after = persistedById(id)
        assertEquals("melonDS (my tweaks)", after.name)
        assertEquals("keep-me", after.intentExtras["myCustomExtra"])
    }

    @Test
    fun `custom profile is never reconciled against the catalog`() = runBlocking {
        val custom = EmulatorProfile(
            id = "custom_my_fork",
            name = "My Fork",
            packageName = "com.example.myfork",
            intentType = IntentType.ACTION_VIEW,
            supportedPlatformIds = listOf("psx"),
            isCustom = true,
        )
        repository.savePersistedProfile(custom)

        service.runOnStartup()

        val after = persistedById("custom_my_fork")
        assertEquals("My Fork", after.name)
        assertTrue(after.isAvailable, "Custom profiles must not be marked unavailable")
    }

    @Test
    fun `auto profile for an uninstalled emulator is marked unavailable`() = runBlocking {
        val id = EmulatorDetector.autoId("org.ppsspp.ppsspp")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = id,
                name = "PPSSPP",
                packageName = "org.ppsspp.ppsspp",
                intentType = IntentType.ACTION_VIEW,
                supportedPlatformIds = listOf("psp"),
                isAutoGenerated = true,
                isAvailable = true,
            )
        )

        service.runOnStartup()

        assertFalse(persistedById(id).isAvailable)
    }

    @Test
    fun `detector maps attachRomData through to the profile`() {
        installPackage("dev.eden.eden_emulator")

        val eden = EmulatorDetector(context).detect()
            .first { it.packageName == "dev.eden.eden_emulator" }

        assertEquals(IntentType.COMPONENT, eden.intentType)
        assertEquals("android.nfc.action.TECH_DISCOVERED", eden.intentAction)
        assertTrue(eden.attachRomData, "attachRomData lost between catalog and profile")
        assertEquals("org.yuzu.yuzu_emu.activities.EmulationActivity", eden.activityClass)
    }
}
