package com.playfieldportal.feature.launcher

import android.content.Context
import android.content.pm.PackageInfo
import androidx.test.core.app.ApplicationProvider
import com.playfieldportal.core.data.repository.CoreInventory
import com.playfieldportal.core.data.repository.RetroArchLink
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.IntentType
import com.playfieldportal.core.domain.model.emulatorkb.EmulatorKbDecode
import com.playfieldportal.core.domain.model.emulatorkb.EmulatorKbDecoder
import com.playfieldportal.core.domain.model.emulatorkb.EmulatorKbDocument
import com.playfieldportal.feature.launcher.kb.EmulatorKnowledgeStore
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.json.Json
import org.junit.Before
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.Shadows.shadowOf
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Startup reconciliation between the catalog and persisted profiles. The critical behavior:
 * untouched auto-profiles must adopt corrected catalog recipes on upgrade, while anything
 * the user edited or created stays untouched.
 */
@RunWith(RobolectricTestRunner::class)
class EmulatorAutoConfigServiceTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val repository = EmulatorProfileRepository(
        context,
        Dispatchers.Unconfined,
        mockk(relaxed = true),
    )
    private val store = EmulatorKnowledgeStore(context, Dispatchers.Unconfined)
    private val detector = EmulatorDetector(context, store)

    // Real link, no stored tree → CoreInventory.Unlinked → no RetroArch cores offered.
    private val service = EmulatorAutoConfigService(
        detector,
        repository,
        com.playfieldportal.core.data.repository.RetroArchLink(context),
    )

    @Before
    fun cleanKnowledgeFiles() {
        java.io.File(context.filesDir, "emulator_kb").deleteRecursively()
    }

    private fun userFile(vararg emulators: String): EmulatorKbDocument {
        val text = """{"format":"pfp-emulator-kb","schemaVersion":1,"version":0,"label":"",
            "emulators":[${emulators.joinToString(",")}],"platforms":[]}"""
        return (EmulatorKbDecoder.decode(text) as EmulatorKbDecode.Decoded).document
    }

    private fun emu(id: String, packages: List<String>, launch: String, extra: String = ""): String {
        val pkgs = packages.joinToString(",") { "\"$it\"" }
        return """{"id":"$id","name":"Emu $id","packageNames":[$pkgs],"platformIds":["psx"],"launch":$launch$extra}"""
    }

    private val viewLaunch = """{"intentType":"ACTION_VIEW","action":"android.intent.action.VIEW"}"""
    private val componentLaunch = """{"intentType":"COMPONENT","activityClass":"com.example.emu.Main"}"""

    private fun installPackage(packageName: String) {
        shadowOf(context.packageManager)
            .installPackage(PackageInfo().apply { this.packageName = packageName })
    }

    /** A service whose RetroArch inventory is fixed, so each [CoreInventory] state is testable. */
    private fun serviceSeeing(state: CoreInventory): EmulatorAutoConfigService {
        val link = mockk<RetroArchLink>()
        coEvery { link.inventory() } returns state
        return EmulatorAutoConfigService(detector, repository, link)
    }

    private fun retroArchCore(fileName: String, platform: String) = EmulatorProfile(
        id                   = EmulatorDetector.retroarchCoreId(fileName),
        name                 = "RetroArch · $fileName",
        packageName          = "com.retroarch",
        activityClass        = EmulatorDetector.RETROARCH_ACTIVITY_CLASS,
        intentType           = IntentType.COMPONENT,
        supportedPlatformIds = listOf(platform),
        coreMap              = mapOf(platform to "/data/data/com.retroarch/cores/$fileName"),
        isAutoGenerated      = true,
        autoSource           = "retroarch-core",
        isAvailable          = true,
    )

    private suspend fun persistedById(id: String): EmulatorProfile =
        repository.getAllPersistedProfiles().first { it.id == id }

    @Test
    fun `untouched auto profile adopts the corrected catalog recipe`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        val staleId = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = staleId,
                name = "DuckStation",
                packageName = "com.github.stenzek.duckstation",
                activityClass = "com.github.stenzek.duckstation.EmulationActivity",
                intentType = IntentType.COMPONENT,
                supportedPlatformIds = listOf("psx", "ps1"),
                intentExtras = mapOf("bootPath" to "{rom_path}"), // pre-fix raw-path recipe
                isAutoGenerated = true,
                createdAt = 1234L,
            )
        )

        service.runOnStartup()

        val refreshed = persistedById(staleId)
        assertEquals(
            "{rom_uri}", refreshed.intentExtras["bootPath"],
            "Stale recipe should be replaced by the current catalog recipe",
        )
        assertEquals(1234L, refreshed.createdAt, "Creation time must survive the refresh")
        assertTrue(refreshed.isAvailable)
        assertFalse(refreshed.userModified)
    }

    @Test
    fun `user modified auto profile is left untouched`() = runBlocking {
        installPackage("me.magnum.melonds")
        val id = EmulatorDetector.autoId("me.magnum.melonds")
        val edited = EmulatorProfile(
            id = id,
            name = "melonDS (my tweaks)",
            packageName = "me.magnum.melonds",
            activityClass = "me.magnum.melonds.ui.emulator.EmulatorActivity",
            intentType = IntentType.COMPONENT,
            supportedPlatformIds = listOf("nds"),
            intentExtras = mapOf("uri" to "{rom_uri}", "myCustomExtra" to "keep-me"),
            isAutoGenerated = true,
            userModified = true,
        )
        repository.savePersistedProfile(edited)

        service.runOnStartup()

        val after = persistedById(id)
        assertEquals("melonDS (my tweaks)", after.name)
        assertEquals("keep-me", after.intentExtras["myCustomExtra"])
    }

    @Test
    fun `custom profile is never reconciled against the catalog`() = runBlocking {
        val custom = EmulatorProfile(
            id = "custom_my_fork",
            name = "My Fork",
            packageName = "com.example.myfork",
            intentType = IntentType.ACTION_VIEW,
            supportedPlatformIds = listOf("psx"),
            isCustom = true,
        )
        repository.savePersistedProfile(custom)

        service.runOnStartup()

        val after = persistedById("custom_my_fork")
        assertEquals("My Fork", after.name)
        assertTrue(after.isAvailable, "Custom profiles must not be marked unavailable")
    }

    @Test
    fun `auto profile for an uninstalled emulator is marked unavailable`() = runBlocking {
        val id = EmulatorDetector.autoId("org.ppsspp.ppsspp")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = id,
                name = "PPSSPP",
                packageName = "org.ppsspp.ppsspp",
                intentType = IntentType.ACTION_VIEW,
                supportedPlatformIds = listOf("psp"),
                isAutoGenerated = true,
                isAvailable = true,
            )
        )

        service.runOnStartup()

        assertFalse(persistedById(id).isAvailable)
    }

    // Regression, the black-screen bug this whole change exists for. These two tests previously
    // asserted the OPPOSITE — that an unlinked RetroArch still offers a full curated core set — and
    // that fabricated set is exactly what shipped users onto cores they had never downloaded:
    // profiles persisted as available, winning the automatic default for every console without a
    // standalone emulator, launching RetroArch with a core path that did not exist.
    @Test
    fun `no retroarch profiles are offered without a core inventory`() = runBlocking {
        installPackage("com.retroarch")

        val profiles = detector.detect(CoreInventory.Unlinked)
            .filter { it.autoSource == "retroarch-core" }

        assertTrue(
            profiles.isEmpty(),
            "Unlinked RetroArch must offer no cores, got ${profiles.map { it.name }}",
        )
    }

    @Test
    fun `only cores present in the inventory are offered`() = runBlocking {
        installPackage("com.retroarch")
        val inventory = CoreInventory.Verified(
            setOf(
                "fceumm_libretro_android.so",   // NES
                "mgba_libretro_android.so",     // GB/GBC/GBA
                "notes.txt",                    // not a core
                "obscure_libretro_android.so",  // a core, but unmapped to any platform
            )
        )

        val profiles = detector.detect(inventory)
            .filter { it.autoSource == "retroarch-core" }

        assertEquals(2, profiles.size, "Only mapped, installed cores may become profiles")
        val platforms = profiles.flatMap { it.supportedPlatformIds }.toSet()
        assertTrue("nes" in platforms)
        assertTrue("gba" in platforms)
        assertFalse("snes" in platforms, "No SNES core is installed, so no SNES core may be offered")

        val nes = profiles.first { "nes" in it.supportedPlatformIds }
        assertEquals(
            "/data/data/com.retroarch/cores/fceumm_libretro_android.so",
            nes.intentExtras["LIBRETRO"],
            "LIBRETRO must name RetroArch's internal core path",
        )
        assertEquals(nes.intentExtras["LIBRETRO"], nes.coreMap["nes"])
    }

    // The read-only invariant: an inventory that cannot prove a core is present cannot prove it is
    // absent. Disabling one on a guess drops it from the launch pool, so without this a lost SAF
    // grant — a RetroArch reinstall is enough — would silently disable working consoles.
    @Test
    fun `an unverifiable inventory never disables a retroarch core`() = runBlocking {
        installPackage("com.retroarch")
        val core = retroArchCore("mgba_libretro_android.so", "gba")
        repository.savePersistedProfile(core)

        // A remembered set that no longer lists the core is stale, not evidence.
        serviceSeeing(CoreInventory.Remembered(setOf("fceumm_libretro_android.so"))).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "A remembered inventory must not disable a core")

        serviceSeeing(CoreInventory.EmptyTree).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "A wrong-folder link must not disable a core")

        serviceSeeing(CoreInventory.Unlinked).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "An unlinked inventory must not disable a core")
    }

    @Test
    fun `a verified inventory does disable a core that is gone`() = runBlocking {
        installPackage("com.retroarch")
        val core = retroArchCore("snes9x_libretro_android.so", "snes")
        repository.savePersistedProfile(core)

        serviceSeeing(CoreInventory.Verified(setOf("mgba_libretro_android.so"))).runOnStartup()

        assertFalse(
            persistedById(core.id).isAvailable,
            "A live read that omits the core is proof it is gone",
        )
    }

    @Test
    fun `detector maps attachRomData through to the profile`() = runBlocking {
        installPackage("dev.eden.eden_emulator")

        val eden = detector.detect()
            .first { it.packageName == "dev.eden.eden_emulator" }

        assertEquals(IntentType.COMPONENT, eden.intentType)
        assertEquals("android.nfc.action.TECH_DISCOVERED", eden.intentAction)
        assertTrue(eden.attachRomData, "attachRomData lost between catalog and profile")
        assertEquals("org.yuzu.yuzu_emu.activities.EmulationActivity", eden.activityClass)
    }

    @Test
    fun `an installed second package yields its own auto id with the knowledge id set`() = runBlocking {
        store.addUserFile("t", userFile(emu("multi", listOf("com.example.first", "com.example.second"), viewLaunch)))
        installPackage("com.example.second")

        val profile = detector.detect().single { it.knowledgeId == "multi" }

        assertEquals(EmulatorDetector.autoId("com.example.second"), profile.id)
        assertEquals("com.example.second", profile.packageName)
    }

    @Test
    fun `a launchByPackage override applies only to its own package`() = runBlocking {
        val builds = emu(
            "builds", listOf("com.example.base", "com.example.alt"), componentLaunch,
            extra = ""","launchByPackage":{"com.example.alt":$viewLaunch}""",
        )
        store.addUserFile("t", userFile(builds))

        installPackage("com.example.alt")
        val alt = detector.detect().single { it.knowledgeId == "builds" }
        assertEquals("com.example.alt", alt.packageName)
        assertEquals(IntentType.ACTION_VIEW, alt.intentType)
        assertEquals(null, alt.activityClass)

        // The sibling without an override uses the entry's base launch.
        installPackage("com.example.base")
        val base = detector.detect().single { it.knowledgeId == "builds" }
        assertEquals("com.example.base", base.packageName)
        assertEquals(IntentType.COMPONENT, base.intentType)
        assertEquals("com.example.emu.Main", base.activityClass)
    }

    @Test
    fun `signer pins are copied onto the detected profile`() = runBlocking {
        val pin = "a".repeat(64)
        store.addUserFile(
            "t",
            userFile(emu("pinned", listOf("com.example.pinned"), viewLaunch, extra = ""","signerSha256":["$pin"]""")),
        )
        installPackage("com.example.pinned")

        assertEquals(listOf(pin), detector.detect().single { it.knowledgeId == "pinned" }.signerSha256)
    }

    @Test
    fun `a user layer override changes an untouched auto profile on refresh`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        service.runOnStartup()
        val id = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        assertEquals("{rom_uri}", persistedById(id).intentExtras["bootPath"])

        val override = """{"intentType":"COMPONENT","activityClass":"com.github.stenzek.duckstation.EmulationActivity","extras":{"bootPath":"{rom_path}"}}"""
        store.addUserFile("t", userFile(emu("duckstation", listOf("com.github.stenzek.duckstation"), override)))
        service.runOnStartup()

        assertEquals("{rom_path}", persistedById(id).intentExtras["bootPath"])
    }

    @Test
    fun `a userModified profile is unchanged by a knowledge change`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        val id = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = id, name = "Mine", packageName = "com.github.stenzek.duckstation",
                intentType = IntentType.ACTION_VIEW, supportedPlatformIds = listOf("psx"),
                isAutoGenerated = true, userModified = true,
            )
        )
        store.addUserFile(
            "t", userFile(emu("duckstation", listOf("com.github.stenzek.duckstation"), componentLaunch)),
        )

        service.runOnStartup()

        assertEquals("Mine", persistedById(id).name)
        assertEquals(IntentType.ACTION_VIEW, persistedById(id).intentType)
    }

    @Test
    fun `an untouched auto profile whose package left the knowledge base is kept but unavailable`() = runBlocking {
        // Kept, not deleted: games and memory cards may still reference its id, and a knowledge base
        // that fails to load must never be able to wipe every detected emulator.
        fun stale(pkg: String, userModified: Boolean) = EmulatorProfile(
            id = EmulatorDetector.autoId(pkg), name = pkg, packageName = pkg,
            intentType = IntentType.ACTION_VIEW, supportedPlatformIds = listOf("psx"),
            isAutoGenerated = true, autoSource = "auto-detected", userModified = userModified,
        )
        repository.savePersistedProfile(stale("com.example.gone", userModified = false))
        repository.savePersistedProfile(stale("com.example.mine", userModified = true))

        service.runOnStartup()

        val byId = repository.getAllPersistedProfiles().associateBy { it.id }
        assertFalse(byId.getValue(EmulatorDetector.autoId("com.example.gone")).isAvailable)
        assertTrue(byId.getValue(EmulatorDetector.autoId("com.example.mine")).isAvailable, "userModified profile is never touched")
    }

    @Test
    fun `persisted json without the knowledge fields still decodes`() {
        val old = """{"id":"x","name":"X","packageName":"com.example.x","intentType":"ACTION_VIEW","supportedPlatformIds":[]}"""

        val decoded = Json.decodeFromString(EmulatorProfile.serializer(), old)

        assertEquals(null, decoded.knowledgeId)
        assertEquals(emptyList(), decoded.signerSha256)
    }

    @Test
    fun `concurrent runs never overlap`() = runBlocking {
        val link = mockk<RetroArchLink>()
        coEvery { link.inventory() } returns CoreInventory.Unlinked
        val repo = mockk<EmulatorProfileRepository>(relaxed = true)
        val active = java.util.concurrent.atomic.AtomicInteger()
        val peak = java.util.concurrent.atomic.AtomicInteger()
        coEvery { repo.getAllPersistedProfiles() } coAnswers {
            peak.accumulateAndGet(active.incrementAndGet()) { a, b -> maxOf(a, b) }
            kotlinx.coroutines.delay(30)
            active.decrementAndGet()
            emptyList()
        }
        val svc = EmulatorAutoConfigService(detector, repo, link)

        List(4) { async(Dispatchers.Default) { svc.runOnStartup() } }
            .forEach { it.await() }

        assertEquals(1, peak.get())
    }
}
