package com.playfieldportal.feature.settings.viewmodel

import com.playfieldportal.core.domain.model.IntentType
import com.playfieldportal.core.domain.model.emulatorkb.EffectiveKbEmulator
import com.playfieldportal.core.domain.model.emulatorkb.EmulatorKbEmulator
import com.playfieldportal.core.domain.model.emulatorkb.EmulatorKbLaunch
import com.playfieldportal.core.domain.model.emulatorkb.KbSource
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** The "Available (Not Installed)" list is built from effective KB entries with no installed package. */
class EmulatorsAvailableListTest {

    private fun effective(id: String, vararg packages: String, type: IntentType = IntentType.ACTION_VIEW) =
        EffectiveKbEmulator(
            emulator = EmulatorKbEmulator(
                id = id,
                name = "Emu $id",
                packageNames = packages.toList(),
                platformIds = listOf("psx"),
                launch = EmulatorKbLaunch(intentType = type),
            ),
            source = KbSource.BuiltIn,
            replaced = null,
        )

    @Test
    fun `an entry with no installed package is listed under its first package`() {
        val items = kbAvailableItems(listOf(effective("a", "org.a.one", "org.a.two", type = IntentType.COMPONENT))) { false }

        assertEquals(1, items.size)
        val item = items.single()
        assertEquals("a", item.id)
        assertEquals("Emu a", item.name)
        assertEquals("org.a.one", item.packageName)
        assertEquals("COMPONENT", item.intentType)
        assertTrue(!item.isCustom && !item.isAutoGenerated)
    }

    @Test
    fun `an entry is hidden when any of its packages is installed`() {
        val entries = listOf(effective("a", "org.a.one", "org.a.two"), effective("b", "org.b"))

        val items = kbAvailableItems(entries) { it == "org.a.two" }

        assertEquals(listOf("b"), items.map { it.id })
    }

    @Test
    fun `no entries yields an empty list`() {
        assertTrue(kbAvailableItems(emptyList()) { false }.isEmpty())
    }
}
