package com.playfieldportal.feature.launcher.kb

import com.playfieldportal.core.data.database.seeder.PlatformSeeder
import com.playfieldportal.core.data.kb.LegacyEmulatorIdRewriter
import com.playfieldportal.core.data.kb.PlatformGain
import com.playfieldportal.core.data.kb.PlatformKnowledgeApplier
import com.playfieldportal.core.domain.model.emulatorkb.EffectiveKbEmulator
import com.playfieldportal.core.domain.model.emulatorkb.KbSource
import com.playfieldportal.feature.launcher.EmulatorAutoConfigService
import com.playfieldportal.feature.launcher.EmulatorDetector
import com.playfieldportal.feature.launcher.EmulatorProfileRepository
import com.playfieldportal.feature.launcher.platformAliases
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

/**
 * The one entry point for "the knowledge base may have changed, bring the emulator profiles in line".
 * Startup and every KB-changing flow (official update, import, remove, reset) call [run] so detection
 * and refresh never disagree about which layers are in force.
 *
 * It applies the KB's platform extensions first (AD-9), runs auto-config, then rewrites stored
 * references to retired bundled ids onto the detected profiles (AD-6). Removing a file or
 * resetting never takes extensions back: platform changes are additive and the applied record is kept.
 */
@Singleton
class EmulatorKnowledgeRefresher @Inject constructor(
    private val store: EmulatorKnowledgeStore,
    private val platformApplier: PlatformKnowledgeApplier,
    private val autoConfig: EmulatorAutoConfigService,
    private val profiles: EmulatorProfileRepository,
    private val legacyRewriter: LegacyEmulatorIdRewriter,
) {
    private val _gainedFileTypes = MutableStateFlow<List<PlatformGain>>(emptyList())

    /**
     * Consoles that gained file types since the app started, for the KB screen's rescan suggestion.
     * Accumulates across runs; a run that gains nothing does not clear it.
     */
    val gainedFileTypes: StateFlow<List<PlatformGain>> = _gainedFileTypes.asStateFlow()

    private val mutex = Mutex()

    /**
     * Runs one at a time, and to completion even if the caller's scope is cancelled, so the KB and
     * the profiles are never left half-applied.
     */
    suspend fun run() {
        withContext(NonCancellable) {
            mutex.withLock {
                applyPlatformKnowledge()
                autoConfig.runOnStartup()
                rewriteLegacyIds()
            }
        }
    }

    /**
     * Retired bundled ids become the `auto_<pkg>` of the entry's installed package; an entry with no
     * installed package is left for a later run. Runs after auto-config so the persisted profiles
     * say what is installed. An id a persisted profile still holds is a user's edited copy, and the
     * bundled shortcut ids are never retired, so both keep their references.
     */
    private suspend fun rewriteLegacyIds() {
        try {
            val persisted = profiles.getAllPersistedProfiles()
            val installed = persisted.filter { it.isAutoGenerated && it.isAvailable }.mapTo(HashSet()) { it.packageName }
            val map = legacyIdMap(store.current().emulators, installed)
            val keepIds = persisted.mapTo(HashSet()) { it.id } + profiles.bundledProfileIds()
            val changed = legacyRewriter.run(map, keepIds)
            if (changed > 0) Timber.i("Rewrote $changed references to retired emulator ids")
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            // A rewrite is a convenience; the old ids keep resolving until it succeeds.
            Timber.e(e, "Rewriting legacy emulator ids failed")
        }
    }

    private suspend fun applyPlatformKnowledge() {
        try {
            val gains = platformApplier.apply(platformExtensions())
            if (gains.isNotEmpty()) _gainedFileTypes.value = merge(_gainedFileTypes.value, gains)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            // Extensions are an extra; a failure here must not stop profile refresh.
            Timber.e(e, "Applying platform knowledge failed")
        }
    }

    /** KB platform ids resolved to the seeded platform they name (an alias such as "ps1" means "psx"). */
    private suspend fun platformExtensions(): Map<String, List<String>> {
        val result = LinkedHashMap<String, List<String>>()
        for (entry in store.current().platforms) {
            val kb = entry.platform
            val id = platformAliases(kb.id).firstOrNull { it in SEEDED_IDS } ?: kb.id
            result[id] = ((result[id] ?: emptyList()) + kb.romExtensions).distinct()
        }
        return result
    }

    private fun merge(current: List<PlatformGain>, gains: List<PlatformGain>): List<PlatformGain> {
        val byId = LinkedHashMap(current.associate { it.platformId to it.added })
        for (gain in gains) byId[gain.platformId] = ((byId[gain.platformId] ?: emptyList()) + gain.added).distinct()
        return byId.map { PlatformGain(it.key, it.value) }
    }

    internal companion object {
        val SEEDED_IDS: Set<String> = PlatformSeeder.DEFAULT_PLATFORMS.map { it.id }.toSet()

        /**
         * Entry ids and legacy ids (the retired bundled profile ids) to the replacing profile id,
         * for entries with an installed package. Only built-in and official entries count: an
         * imported file must not be able to redirect stored references to its own package.
         */
        fun legacyIdMap(emulators: List<EffectiveKbEmulator>, installedPackages: Set<String>): Map<String, String> {
            val map = LinkedHashMap<String, String>()
            for (effective in emulators) {
                if (effective.source != KbSource.BuiltIn && effective.source != KbSource.Official) continue
                val entry = effective.emulator
                val pkg = entry.packageNames.firstOrNull { it in installedPackages } ?: continue
                val target = EmulatorDetector.autoId(pkg)
                for (legacy in listOf(entry.id) + entry.legacyIds) map.putIfAbsent(legacy, target)
            }
            return map
        }
    }
}
