package com.playfieldportal.feature.launcher

import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class EmulatorAutoConfigService @Inject constructor(
    private val detector: EmulatorDetector,
    private val repository: EmulatorProfileRepository,
) {

    suspend fun runOnStartup() {
        val existing = repository.getAllPersistedProfiles()
        val detected = detector.detect()
        val now = System.currentTimeMillis()
        var added = 0
        var refreshed = 0

        for (profile in detected) {
            val match = existing.firstOrNull { it.id == profile.id }
            when {
                match == null -> {
                    // No entry yet — create auto-generated entry
                    repository.savePersistedProfile(profile)
                    added++
                }
                match.isAutoGenerated && !match.userModified -> {
                    // Auto entry not touched by user — refresh availability + timestamp only
                    repository.savePersistedProfile(
                        match.copy(isAvailable = true, lastDetectedAt = now)
                    )
                    refreshed++
                }
                // isCustom or userModified: user owns this entry, leave it untouched
            }
        }

        // Mark auto-generated entries whose emulator is no longer installed
        val detectedIds = detected.map { it.id }.toSet()
        var markedUnavailable = 0
        for (entry in existing) {
            if (entry.isAutoGenerated && !entry.userModified && entry.id !in detectedIds && entry.isAvailable) {
                repository.savePersistedProfile(entry.copy(isAvailable = false))
                markedUnavailable++
            }
        }

        Timber.i("EmulatorAutoConfig: +$added new, $refreshed refreshed, $markedUnavailable marked unavailable")
    }
}
