package com.playfieldportal.feature.launcher

import com.playfieldportal.core.data.repository.RetroArchLink
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class EmulatorAutoConfigService @Inject constructor(
    private val detector: EmulatorDetector,
    private val repository: EmulatorProfileRepository,
    private val retroArchLink: RetroArchLink,
) {

    suspend fun runOnStartup() {
        // When RetroArch is linked, this is the authoritative set of installed cores so detection
        // offers only cores that exist; null when unlinked (offer curated defaults unverified).
        val installedRetroArchCores = retroArchLink.installedCoreFiles()
        val existing = repository.getAllPersistedProfiles()
        val detected = detector.detect(installedRetroArchCores)
        val now = System.currentTimeMillis()
        var added = 0
        var refreshed = 0

        for (profile in detected) {
            val match = existing.firstOrNull { it.id == profile.id }
            when {
                match == null -> {
                    // No entry yet — create auto-generated entry
                    repository.savePersistedProfile(profile)
                    added++
                }
                match.isAutoGenerated && !match.userModified -> {
                    // Auto entry not touched by user — adopt the freshly detected profile so
                    // catalog recipe corrections reach existing installs, keeping creation time.
                    repository.savePersistedProfile(
                        profile.copy(createdAt = match.createdAt, lastDetectedAt = now)
                    )
                    refreshed++
                }
                // isCustom or userModified: user owns this entry, leave it untouched
            }
        }

        // Mark auto-generated entries whose emulator is no longer installed
        val detectedIds = detected.map { it.id }.toSet()
        var markedUnavailable = 0
        for (entry in existing) {
            if (entry.isAutoGenerated && !entry.userModified && entry.id !in detectedIds && entry.isAvailable) {
                repository.savePersistedProfile(entry.copy(isAvailable = false))
                markedUnavailable++
            }
        }

        Timber.i("EmulatorAutoConfig: +$added new, $refreshed refreshed, $markedUnavailable marked unavailable")
    }
}
