package com.playfieldportal.feature.launcher

import android.content.Context
import android.content.pm.PackageManager
import com.playfieldportal.core.domain.model.EmulatorProfile
import com.playfieldportal.core.domain.model.IntentType
import dagger.hilt.android.qualifiers.ApplicationContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Discovers installed emulators and turns them into launchable [EmulatorProfile]s.
 *
 * Two sources: the curated [KnownEmulatorCatalog] (one profile per installed package) and RetroArch
 * (one profile per installed libretro core). Run on startup by [EmulatorAutoConfigService], which
 * persists the results without clobbering the user's own edits.
 */
@Singleton
class EmulatorDetector @Inject constructor(
    @ApplicationContext private val context: Context,
) {

    fun detect(): List<EmulatorProfile> {
        val pm = context.packageManager
        val results = mutableListOf<EmulatorProfile>()
        val now = System.currentTimeMillis()

        // Scan for standard emulators from the catalog
        for (known in KnownEmulatorCatalog.entries) {
            val installedPkg = known.packageNames.firstOrNull { pkg ->
                try { pm.getPackageInfo(pkg, 0); true }
                catch (_: PackageManager.NameNotFoundException) { false }
            } ?: continue

            results += EmulatorProfile(
                id                   = autoId(installedPkg),
                name                 = known.suggestedName,
                packageName          = installedPkg,
                intentType           = known.intentType,
                activityClass        = known.activityClass,
                supportedPlatformIds = known.platformIds,
                intentExtras         = known.intentExtras,
                intentBoolExtras     = known.intentBoolExtras,
                intentAction         = known.intentAction,
                intentFlags          = known.intentFlags,
                intentCategory       = known.intentCategory,
                mimeType             = known.mimeType,
                useSafUri            = known.useSafUri,
                isAutoGenerated      = true,
                autoSource           = "auto-detected",
                lastDetectedAt       = now,
                isAvailable          = true,
            )
        }

        // RetroArch: one profile per installed core
        val retroarchPkg = RetroArchCoreScanner.RETROARCH_PACKAGES.firstOrNull { pkg ->
            try { pm.getPackageInfo(pkg, 0); true }
            catch (_: PackageManager.NameNotFoundException) { false }
        }
        if (retroarchPkg != null) {
            val cores = RetroArchCoreScanner.scan()
            Timber.i("RetroArch detected ($retroarchPkg): ${cores.size} mapped cores found")
            for (core in cores) {
                results += EmulatorProfile(
                    id                   = retroarchCoreId(core.fileName),
                    name                 = "RetroArch · ${core.name}",
                    packageName          = retroarchPkg,
                    intentType           = IntentType.COMPONENT,
                    activityClass        = RETROARCH_ACTIVITY_CLASS,
                    supportedPlatformIds = core.platformIds,
                    intentExtras         = mapOf(
                        "ROM"      to "{rom_path}",
                        "LIBRETRO" to core.absolutePath,
                    ),
                    coreMap              = core.platformIds.associateWith { core.absolutePath },
                    isAutoGenerated      = true,
                    autoSource           = "retroarch-core",
                    lastDetectedAt       = now,
                    isAvailable          = true,
                )
            }
        }

        Timber.i(
            "EmulatorDetector: ${results.size} profiles detected " +
            "(${results.count { it.autoSource == "retroarch-core" }} RetroArch cores)"
        )
        return results
    }

    companion object {
        // RetroArch's main activity class is the same regardless of which package variant is
        // installed (com.retroarch, com.retroarch.aarch64, com.retroarch.ra32). The package name
        // is NOT part of the activity class — using "$package.browser.RetroActivity" is wrong
        // and causes ActivityNotFoundException at launch time.
        const val RETROARCH_ACTIVITY_CLASS = "com.retroarch.browser.retroactivity.RetroActivityFuture"

        fun autoId(packageName: String): String =
            "auto_${packageName.replace('.', '_')}"

        fun retroarchCoreId(fileName: String): String =
            "auto_retroarch_${fileName.removeSuffix(".so").replace('-', '_')}"
    }
}
