package com.playfieldportal.core.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class EmulatorProfile(
    val id: String,
    val name: String,
    val packageName: String,
    val activityClass: String? = null,
    val intentType: IntentType,
    val supportedPlatformIds: List<String>,
    val intentExtras: Map<String, String> = emptyMap(),         // key → string value template
    val intentBoolExtras: Map<String, Boolean> = emptyMap(),   // key → boolean value (e.g. resumeState=false)
    // key → array of value templates. Needed by ID-launch emulators like Vita3K, whose
    // AppStartParameters = ["-r", "{title_id}"] boots an installed title rather than a ROM file.
    val intentArrayExtras: Map<String, List<String>> = emptyMap(),
    val intentAction: String? = null,    // overrides ACTION_MAIN for COMPONENT intents
    val intentFlags: List<String> = emptyList(),             // "CLEAR_TASK" | "CLEAR_TOP" | "NEW_TASK"
    val intentCategory: String? = null,  // e.g. "android.intent.category.LEANBACK_LAUNCHER"
    // COMPONENT intents only: also set the ROM content:// URI as the intent data. Needed by
    // emulators whose EmulationActivity filter matches on action + data rather than extras
    // (e.g. the yuzu lineage's android.nfc.action.TECH_DISCOVERED quirk).
    val attachRomData: Boolean = false,
    // COMPONENT intents only: a template for the intent data (a deep link carrying the game, e.g.
    // X360 Mobile's "x360mobile://launch?uri={rom_file_uri_encoded}"). Null sets no such data.
    val dataUri: String? = null,
    val coreMap: Map<String, String> = emptyMap(),           // platformId → core path
    val mimeType: String? = null,
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String? = null,                       // overrides all if set
    val minVersionCode: Int? = null,
    val notes: String? = null,
    // File extensions this emulator handles (informational; scanning uses the platform's list).
    val supportedExtensions: List<String> = emptyList(),
    val createdAt: Long? = null,
    val updatedAt: Long? = null,
    val isCustom: Boolean = false,                           // user-created profile
    // Auto-generation metadata — unset for custom and bundled shortcut profiles
    val isAutoGenerated: Boolean = false,
    val autoSource: String? = null,          // "auto-detected" | "retroarch-core"
    val lastDetectedAt: Long? = null,
    val userModified: Boolean = false,       // true once user edits an auto-gen entry
    val isAvailable: Boolean = true,         // false when emulator was uninstalled
    // The knowledge-base entry this profile was detected from (stable KB id); null for custom profiles.
    val knowledgeId: String? = null,
    // Lower-case hex SHA-256 signing-certificate pins copied from the KB entry; empty means no pin.
    val signerSha256: List<String> = emptyList(),
)

@Serializable
enum class IntentType {
    ACTION_VIEW,
    COMPONENT,
    SHORTCUT,
    CUSTOM_COMMAND,
}

// Template variables resolved at launch time
object LaunchTemplate {
    const val ROM_PATH    = "{rom_path}"   // raw filesystem path
    const val ROM_URI     = "{rom_uri}"    // content:// URI string (FileProvider)
    const val ROM_NAME    = "{rom_name}"
    const val ROM_DIR     = "{rom_dir}"
    const val CORE_PATH   = "{core_path}"
    const val CONFIG_PATH = "{config_path}"
    const val PACKAGE     = "{package}"
    const val PLATFORM    = "{platform}"
    const val TITLE_ID    = "{title_id}"   // per-game launch token (e.g. Vita3K installed Title ID)
    const val ROM_FILE_URI = "{rom_file_uri}"                  // file:// URI of the raw path
    const val ROM_FILE_URI_ENCODED = "{rom_file_uri_encoded}"  // the same, encoded as a query value
}

/** Pure URI builders behind the file-URI templates, so the exact strings are JVM-testable. */
object LaunchUris {
    // RFC 3986 unreserved characters plus the sub-delims and ':' '@' a path segment may carry as-is.
    private const val PATH_SAFE = "-._~!$&'()*+,;=:@"

    /** `/a b/c.iso` → `file:///a%20b/c.iso`: only what a URI path cannot hold is escaped. */
    fun fileUriOf(path: String): String = "file://" + path.split('/').joinToString("/") { segment ->
        buildString {
            for (byte in segment.toByteArray(Charsets.UTF_8)) {
                val c = byte.toInt().toChar()
                if (byte >= 0 && (c.isLetterOrDigit() || c in PATH_SAFE)) append(c)
                else append('%').append("%02X".format(byte.toInt() and 0xFF))
            }
        }
    }

    /** Encodes [value] for use as one query parameter value (everything but unreserved is escaped). */
    fun queryEncode(value: String): String =
        java.net.URLEncoder.encode(value, "UTF-8").replace("+", "%20")
}
