package com.playfieldportal.core.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class EmulatorProfile(
    val id: String,
    val name: String,
    val packageName: String,
    val activityClass: String? = null,
    val intentType: IntentType,
    val supportedPlatformIds: List<String>,
    val intentExtras: Map<String, String> = emptyMap(),         // key → string value template
    val intentBoolExtras: Map<String, Boolean> = emptyMap(),   // key → boolean value (e.g. resumeState=false)
    val intentAction: String? = null,    // overrides ACTION_MAIN for COMPONENT intents
    val intentFlags: List<String> = emptyList(),             // "CLEAR_TASK" | "CLEAR_TOP" | "NEW_TASK"
    val intentCategory: String? = null,  // e.g. "android.intent.category.LEANBACK_LAUNCHER"
    val coreMap: Map<String, String> = emptyMap(),           // platformId → core path
    val mimeType: String? = null,
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String? = null,                       // overrides all if set
    val minVersionCode: Int? = null,
    val notes: String? = null,
    // File extensions this emulator handles (informational; scanning uses the platform's list).
    val supportedExtensions: List<String> = emptyList(),
    val createdAt: Long? = null,
    val updatedAt: Long? = null,
    val isCustom: Boolean = false,                           // user-created profile
    // Auto-generation metadata — ignored for bundled profiles
    val isAutoGenerated: Boolean = false,
    val autoSource: String? = null,          // "auto-detected" | "retroarch-core"
    val lastDetectedAt: Long? = null,
    val userModified: Boolean = false,       // true once user edits an auto-gen entry
    val isAvailable: Boolean = true,         // false when emulator was uninstalled
)

@Serializable
enum class IntentType {
    ACTION_VIEW,
    COMPONENT,
    SHORTCUT,
    CUSTOM_COMMAND,
}

// Template variables resolved at launch time
object LaunchTemplate {
    const val ROM_PATH    = "{rom_path}"   // raw filesystem path
    const val ROM_URI     = "{rom_uri}"    // content:// URI string (FileProvider)
    const val ROM_NAME    = "{rom_name}"
    const val ROM_DIR     = "{rom_dir}"
    const val CORE_PATH   = "{core_path}"
    const val CONFIG_PATH = "{config_path}"
    const val PACKAGE     = "{package}"
    const val PLATFORM    = "{platform}"
}
